spring.application.name=exerciciosb

spring.datasource.url=jdbc:postgresql://localhost:5432/springboot
spring.datasource.username=postgres
spring.datasource.password=C3cbczzZ*

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
